### ISSUE TITLE
Error: Could not find executable python

### ISSUE THREAD

**Issue by ashinonyx** [mattwarkentin/torontodown#9]
I've been trying to render my thesis, which worked just fine until a few weeks ago. It's been throwing the following error:

```
Error running filter /Library/Frameworks/R.framework/Versions/4.2/Resources/library/torontodown/pandoc/hide-header.py:
Could not find executable python
Error: pandoc document conversion failed with error 83
```

I've tried initializing python and setting the python location with reticulate, but these don't seem to help at all. Any insights?

**Comment by mattwarkentin** [comment]
Hi @ashinonyx,

Are you using the RStudio IDE? If so, what shows up when you go into `Tools > Global Options > Python` (or alternatively `Tools > Project Options > Python`)?

Seems like the issue is that pandoc isn't able to find a Python interpreter in which to run the Python filter. I think `{reticulate}` sets the Python interpreter for the current session, but the thesis document is built in a separate clean session and so we need to make sure the Python interpreter is found at run-time.

**Comment by ashinonyx** [comment]
Thanks for the quick response, @mattwarkentin!

Yes, I'm using RStudio. I do have a Python interpreter set up in the global options, but am still getting the same error.

**Comment by mattwarkentin** [comment]
Hmm, well we have a couple options:
1. I can change the `thesis_pdf()` format so that the `hide-header.py` filter is not used by default and is opt-in/opt-out. This will make it so access to a python interpreter is no longer required
2. I can rewrite the filter in Lua so a python interpreter is no longer necessary for that filter.

Both are feasible. The only issue is whether or not you intend to use the "list of abbreviations" filter. This filter will automatically produce an ordered list of abbreviations in the opening part of your thesis document. This filter is more complicated and also required python.

Actually the last option would be to rewrite the package to use Quarto instead of R Markdown. This has been on my todo list (see https://github.com/mattwarkentin/torontodown/issues/8). This would be the best solution of all, but require the most effort.

If you don't care about the list of abbreviation feature, I can quickly implement 1 or 2, but if you do want this feature I will either rewrite all filters in Lua, or convert to Quarto.

**Comment by mattwarkentin** [comment]
I have begun rewriting this package using Quarto. There are a few friction points that need to be solved before its ready. In the meantime, I am almost done rewriting the Python filters in Lua so Python will no longer be needed. I should've done this before but I was being lazy as I was doing it for myself...

Related: https://github.com/quarto-dev/quarto-cli/discussions/4024

**Comment by ashinonyx** [comment]
Thanks so much, @mattwarkentin! I shouldn't need the list of abbreviations feature, so the Lua option you're working on now should work well for me.

**Comment by mattwarkentin** [comment]
As of 08558853a4208fddc546bea49d7eb8c730ef04d6, there is no requirement for Python for the default usage of this package. @ashinonyx Please re-install the package and let me know if you have any issues.

**Comment by ashinonyx** [comment]
Thanks, @mattwarkentin! Everything seems to be working well now :)
